title: ajdevhub
description: Projects and Learning Resources
author: Ajay Kumar Gupt
baseurl: ""
url: "https://ajay3007.github.io"

# Social / SEO
twitter_username: ajay3007
github_username: Ajay3007
og_image: /assets/images/og-default.png # default Open Graph image

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    block:
      line_numbers: false

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:slug/
  learning:
    output: true
    permalink: /learning/:path/
  editorials:
    output: true
    permalink: /editorials/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - scripts/
  - README.md
  - Gemfile
  - Gemfile.lock
