title: ajdevhub
description: Projects and Learning Resources
author: Ajay Kumar Gupt
baseurl: ""
url: "https://ajay3007.github.io"

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:slug/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - scripts/
  - README.md
  - Gemfile
  - Gemfile.lock